name: Build and Publish ESPHome firmware and website

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish-m5stack-atom-lite:
    name: Publish M5Stack Atom Lite
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: m5stack-atom-lite.yaml
      name: M5 Stack Atom Lite
      manifest_filename: m5stack-atom-lite-manifest.json
      clean: false
      esphome_version: beta

  publish-esp32-generic:
    name: Publish ESP32 Generic
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: esp32-generic.yaml
      name: ESP32 Generic
      manifest_filename: esp32-generic-manifest.json
      clean: false
      esphome_version: beta

  publish-olimex-esp32-poe-iso:
    name: Publish Olimex PoE ISO
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: olimex-esp32-poe-iso.yaml
      name: Olimex PoE ISO
      manifest_filename: olimex-esp32-poe-iso-manifest.json
      clean: false
      esphome_version: beta

  publish-wt32-eth01:
    name: Publish Wireless-Tag WT32-ETH01
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: wt32-eth01.yaml
      name: Wireless-Tag WT32-ETH01
      manifest_filename: wt32-eth01-manifest.json
      clean: false
      esphome_version: beta

  publish-gl-s10:
    name: Publish GL.iNet GL-S10
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: gl-s10.yaml
      name: GL.iNet GL-S10
      manifest_filename: gl-s10-manifest.json
      clean: false
      esphome_version: beta

  publish-lilygo-t-eth-poe:
    name: Publish LilyGO T-ETH-POE ESP32-WROOM
    uses: esphome/workflows/.github/workflows/publish.yml@main
    with:
      files: lilygo-t-eth-poe.yaml
      name: LilyGO T-ETH-POE
      manifest_filename: lilygo-t-eth-poe-manifest.json
      clean: false
      esphome_version: beta
